databases:
  - name: anime-snake-arena-db
    plan: starter

services:
  - type: web
    name: anime-snake-arena
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/leaderboard
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anime-snake-arena-db
          property: connectionString
      - key: PORT
        value: 80
